### ISSUE TITLE
Error when calling :Buffers

### ISSUE THREAD

**Issue by SanchayanMaity** [LoricAndre/fzterm.nvim#1]
I encounter an error when calling `:Buffers` as in the attached screen shot. neovim version is latest nightly.

![2020-11-02-165556_3838x2126_scrot](https://user-images.githubusercontent.com/5573968/97863663-5911ba80-1d2d-11eb-9d7f-ab7a9cb2a5c9.png)

**Comment by LoricAndre** [comment]
I just fixed the blank line, which would remove the broken preview window message

**Comment by SanchayanMaity** [comment]
Thank you very much. Seems fixed now. Closing the issue.
