### ISSUE TITLE
Filetype not set after opening a file

### ISSUE THREAD

**Issue by RefusesNames** [LoricAndre/fzterm.nvim#12]
After opening a file (using `:GFiles` if that matters) I am greeted with a file without any syntax highlighting and and
```
set filetype?
```
results in 
```
filetype=
```
I can set the filetype by just reloading the file using `:e`, but that is obviously not really convenient.

**Comment by LoricAndre** [comment]
Hi, I think this should work now, can you check it out pls ?

**Comment by RefusesNames** [comment]
It works, but I receive an error message:
![image](https://user-images.githubusercontent.com/823148/98119592-17a81900-1ead-11eb-95da-369ade27b580.png)
Tested it with multiple filetypes and it happened for all of them.

Since the original problem is solved, should I close this issue and create a new one for the new problem?

**Comment by LoricAndre** [comment]
It would be perfect yes, and could you add a way to reproduce this pls ?
