### ISSUE TITLE
[Bug Report] Inserting "R>" after escaping

### ISSUE THREAD

**Issue by theniceboy** [LoricAndre/fzterm.nvim#2]
When I do `:Files` and then press escape, nvim will go into insert mode and type "R>" (without quotes) for some reason.

```
:version
NVIM v0.5.0-df72640
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshado
w -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS
 -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20201023-57691-12hx77c/build/config -I/tmp/neovim-20201023-
57691-12hx77c/src -I/usr/local/include -I/tmp/neovim-20201023-57691-12hx77c/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/usr/in
clude -I/usr/local/opt/gettext/include -I/tmp/neovim-20201023-57691-12hx77c/build/src/nvim/auto -I/tmp/neovim-20201023-57691-12hx77c/build/include
Compiled by david@MacBook-Pro.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-df72640/share/nvim"

Run :checkhealth for more info
```

**Comment by LoricAndre** [comment]
Hi, can you pls run `:verbose au TermLeave` and post the output here ?

**Comment by theniceboy** [comment]
```
:verbose au TermLeave
--- Autocommands ---
Press ENTER or type command to continue
```

**Comment by LoricAndre** [comment]
Oh sorry I was wrong, it's `TermClose`

**Comment by theniceboy** [comment]
```
:verbose au TermClose
--- Autocommands ---
coc_nvim  TermClose
    *         call s:Autocmd('TermClose', +expand('<abuf>'))
        Last set from ~/.config/nvim/plugged/coc.nvim/plugin/coc.vim line 262
TermClose
    *         call feedkeys('\<CR>')
        Last set from ~/.config/nvim/plugged/fzterm.nvim/plugin/fzterm.vim
Press ENTER or type command to continue
```

**Comment by theniceboy** [comment]
![bug](https://user-images.githubusercontent.com/8187501/97870573-18766900-1d4e-11eb-8f7f-2df29ccf412d.gif)

**Comment by LoricAndre** [comment]
I tried to fix it with the last commit https://github.com/LoricAndre/fzterm.nvim/commit/0c77403294743a0b78b35d36865b5148d551f804

**Comment by theniceboy** [comment]
Ok it doesn't insert text anymore but the cursor moves after escaping
![bug2](https://user-images.githubusercontent.com/8187501/97871304-4314f180-1d4f-11eb-807a-cf8e9e5030f8.gif)

**Comment by theniceboy** [comment]
Also if I do `:Files` in an empty buffer, it will actually change the state of the buffer to "modified"

(doing `:Files` in any buffer will "modify" the buffer but I don't see any visual changes)

**Comment by theniceboy** [comment]
![bug3](https://user-images.githubusercontent.com/8187501/97871686-ccc4bf00-1d4f-11eb-9610-23d04a84115e.gif)

**Comment by LoricAndre** [comment]
Can you check it out now ? I changed the way I handled closing the terminal

**Comment by theniceboy** [comment]
Awesome! The issue has been fixed!

**Comment by theniceboy** [comment]
Please consider looking into #3 and #4

**Comment by LoricAndre** [comment]
Sorry to reopen this, but the way I fixed it broke other functionalities, could you please checkout to the changes I merged to main ?
