### ISSUE TITLE
[Feature Request] Ignoring files and directories

### ISSUE THREAD

**Issue by theniceboy** [LoricAndre/fzterm.nvim#3]
I'm currently using Leaderf for fuzzy file finding and it has a crucial feature: ignoring file/dirs with patterns

Example: 
```
let g:Lf_WildIgnore = {
        \ 'dir': ['.git', 'vendor', 'node_modules'],
        \ 'file': ['__vim_project_root']
        \}
```
This is a pretty important feature and I'd love to see this implemented. The speed of this plugin is outstanding! Great job!

**Comment by LoricAndre** [comment]
This should be implemented in the last few commits
