### ISSUE TITLE
The speed of the plugin decreases dramatically since I tested it yesterday

### ISSUE THREAD

**Issue by theniceboy** [LoricAndre/fzterm.nvim#6]
Thank you for your work on this plugin! Yesterday when I was testing it, the startup time was blazing fast, way faster than FZF, Leaderf, and Clap. However, when I was testing it today, it slowed down. There is a ~400 ms of startup time. I did some testing and it seems like 48c4022f is the last commit that I can get the fast startup time. Not sure what's going on. Also, I was having a hard time understanding your commit messages lol XD  love it tho

**Comment by theniceboy** [comment]
Did some further testing with your code and I'm pretty sure the very line that caused the performance issue is
```lua
  api.nvim_command(':set ft=fzterm')
```
not sure why tho

**Comment by LoricAndre** [comment]
This was linked to how I fixed #2, I changed it and it should be better now
