### ISSUE TITLE
what would a config look like?

### ISSUE THREAD

**Issue by zzzeyez** [LoricAndre/fzterm.nvim#7]
hi, firstly, i love the plugin and it is shaping to become a replacement for other plugins of mine

however, i can not seem to affect the way that `:Files` runs by default

i currently am placing the following code in the file `~/.config/nvim/lua/_fzterm.lua` as well as doing `require "_fzterm"
` in my `init.lua` file

```lua
M = {}

M.Files = function()
  local pre_cmd = "fd --hidden --exclude /library --exclude /.origin --exclude /.thugpro . ~"
  local matcher = "fzf" --preview -m 'bat --theme=base16 --style=changes'"
  M.fzterm(pre_cmd, false, matcher, false)
end

return M
```

**Comment by LoricAndre** [comment]
Hi, thanks for reporting this, it should allow me to update the README with clearer instructions.
Basically, your code isn't linked to my plugin, you just created a method for a random `M` object.
What you want to do is something like : 
```lua
local fzterm = require'fzterm'
fzterm.files = function() -- No capitalized f
    local pre_cmd = "fd --hidden --exclude /library --exclude /.origin --exclude /.thugpro . ~"
    local matcher = "fzf" --preview -m 'bat --theme=base16 --style=changes'"
    fzterm.fzterm(pre_cmd, false, matcher, false)
end
```
And you should be able to call your function using `:Files`

**Comment by zzzeyez** [comment]
awesome, this makes more sense now.  so, below is my functioning config (in case future users want to see)

```lua
local fzterm = require'fzterm'

fzterm.files = function() -- No capitalized f
  local pre_cmd = "fd --type file --hidden --exclude /library --exclude /.origin --exclude /.thugpro --exclude /.cache . ~"
  local matcher = "fzf --exact --preview 'bat --color=always --style=changes --theme=base16 {}'"
  fzterm.fzterm(pre_cmd, false, matcher, false)
end

fzterm.buffers = function() -- No capitalized f
  local matcher = "fzf -m --preview 'bat --color=always --style=changes --theme=base16 {2}' -d '\"'"
  fzterm.fzterm(":ls", "cut -d'\"' -f2", matcher, true)
end
```
