### ISSUE TITLE
Option to disable builtin commands

### ISSUE THREAD

**Issue by khalidchawtany** [LoricAndre/fzterm.nvim#8]
I have another Ag command, when nvim starts I get the following error:
```vim
|| E174: Command already exists: add ! to replace it: Ag lua require'fzterm'.ag()

```
The user should be able to disable builtin commands and provide their own.
https://github.com/LoricAndre/fzterm.nvim/blob/8648af6ddbb2ef80311fc425c35e52578c1bcc7e/plugin/fzterm.vim#L2-L7

**Comment by LoricAndre** [comment]
This should be implemented now, see `g:fzterm_disable_com`
