### ISSUE TITLE
[Bug Report] C:/tmp folder required under Windows

### ISSUE THREAD

**Issue by RefusesNames** [LoricAndre/fzterm.nvim#9]
When using `:GFiles` under Windows the floating window displays the error message
```
Out-File: Could not find a part of the path 'C:\tmp\fzterm'.
```
And after closing the floating window the messages read
```
Error detected while processing BufEnter Autocommands for "*":
E484: Can't open file /tmp/fzterm
```
This problem can be fixed by creating a folder `tmp` in `C:`, but you might want to either document this fix or ensure the existance of this folder yourself.

**Comment by LoricAndre** [comment]
This should be fixed, but I can't test it extensively on my side, can you try it out please ?

**Comment by RefusesNames** [comment]
It works. Thank you for your time.
